# This is a boilerplate parameters config generated for pipeline 'model_create'
# using Kedro 0.18.6.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://kedro.readthedocs.io/en/0.18.6/kedro_project_setup/configuration.html#parameters

create_params:
  learning_rate: 0.001

  # CNN params
  channels_out: 512
  kernel_size: 5